services:
  dev:
    build: .
    
    volumes:
      - .:/workspace:rshared 
    
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    privileged: true
   
    
    # Enable debugging
    ports:
      - "5678:5678"  # for debugpy
    # Add these for better development experience
    tty: true        # Keeps container running and provides terminal
    stdin_open: true # Enables interactive sessions